/*-
 * WSDL stubs for:  http://ws.its.washington.edu:9090/transit/mybus/services/MybusService?WSDL
 *   Generated by:  michael
 *           Date:  Tue Apr  8 00:51:31 2008
 *        Emitter:  Objective-C
 */

#import "MybusService.h"

/*-
 *   Method Name:  getEventData
 * Documentation:  <no documentation>
 */
@implementation getEventData
- (void) setParameters:(NSString*) in_in0 in_in1:(SInt32) in_in1 in_in2:(SInt32) in_in2 in_in3:(SInt32) in_in3
{
    id _paramValues[] = {    
        in_in0,        
        [NSNumber numberWithInt: in_in1],        
        [NSNumber numberWithInt: in_in2],        
        [NSNumber numberWithInt: in_in3],        
    };    
    NSString* _paramNames[] = {    
        @"in0",        
        @"in1",        
        @"in2",        
        @"in3",        
    };    
    [super setParameters:4 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"ns1:getEventDataReturn"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://ws.its.washington.edu:9090/transit/mybus/services/MybusService"            
                 methodName: @"getEventData"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @""            
            methodNamespace: @"http://mybus.transit.ws.its.washington.edu"            
        ];        
}

@end; /* getEventData */


/*-
 *   Method Name:  getAgencies
 * Documentation:  <no documentation>
 */
@implementation getAgencies
- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"ns1:getAgenciesReturn"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://ws.its.washington.edu:9090/transit/mybus/services/MybusService"            
                 methodName: @"getAgencies"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @""            
            methodNamespace: @"http://mybus.transit.ws.its.washington.edu"            
        ];        
}

@end; /* getAgencies */


/*-
 *   Method Name:  getTime
 * Documentation:  <no documentation>
 */
@implementation getTime
- (id) resultValue
{	
    return [[super getResultDictionary] objectForKey: @"ns1:getTimeReturn"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://ws.its.washington.edu:9090/transit/mybus/services/MybusService"            
                 methodName: @"getTime"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @""            
            methodNamespace: @"http://mybus.transit.ws.its.washington.edu"            
        ];        
}

@end; /* getTime */



@implementation MybusService

+ (id) getEventData:(NSString*) in_in0 in_in1:(SInt32) in_in1 in_in2:(SInt32) in_in2 in_in3:(SInt32) in_in3
{
    id result = NULL;    
    getEventData* _invocation = [[getEventData alloc] init];    
    [_invocation setParameters: in_in0 in_in1:in_in1 in_in2:in_in2 in_in3:in_in3];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}


+ (id) getAgencies
{
    id result = NULL;    
    getAgencies* _invocation = [[getAgencies alloc] init];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}


+ (id) getTime
{
    id result = NULL;    
    getTime* _invocation = [[getTime alloc] init];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}



@end;


/*-
 * End of WSDL document at
 * http://ws.its.washington.edu:9090/transit/mybus/services/MybusService?WSDL
 */
